export {default as Navbar} from "./navbar"
export { default as Hero } from "./hero"
export { default as Benefits } from "./benefits"
export { default as AboutSection } from "./aboutSection"
export { default as BtnTitle } from "./btnTitle"
export { default as WhyChoseUs } from "./whyChoseUs"
export { default as Products } from "./products"
export { default as OurStory } from "./ourStory"
export { default as StatsSection } from "./statsSection"
export { default as AutoScroller } from "./autoScroller"
export { default as Product } from "./product"
export { default as AboutPageSection } from "./aboutPageSection"
export { default as AboutHero } from "./aboutHero"
export { default as Contact } from "./contact"
export { default as Footer } from "./footer"