import { Geist, Geist_Mono } from "next/font/google";
import { Navbar } from "./components";
import "./globals.css";
import Footer from "./components/footer";
import { Sora } from 'next/font/google';
import { Roboto } from 'next/font/google'

const roboto = Roboto({
    subsets: ['latin'],
    weight: ['400', '600', '700', '800'],
})

const sora = Sora({
    subsets: ['latin'],
    weight: ['400', '600', '700'], // choose weights you need
    // display: 'swap',
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Aspire Packaging -Your packaging partner in growth",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
